# PUC Minas Virtual

## Métodos de Programação Aplicados ao Mercado Financeiro

Este é o 12º notebook da nossa disciplina, sobre as bibliotecas SciPy e Pandas.

Autor: Prof. Leopoldo Grajeda

Data da última atualização: 01/04/2023

In [1]:
# A biblioteca SciPy reúne as ferramentas matemáticas do Cálculo Avançado.

import numpy as np
import scipy.integrate as integrate  # Pacote de integração numérica
import scipy.optimize as optimize    # Pacote de otimização
import scipy.stats as stats          # Pacote estatístico

### Integração Numérica (SciPy)

In [2]:
# Definição da função a ser integrada
def f(x):
    return np.exp(-x**2)

In [3]:
# Cálculo da integral definida
I, erro = integrate.quad(f,0,1)

# Exibição do valor calculado e da margem de erro
print(f'Valor da integral: {I:.15f}')
print(f'Margem de erro: {erro:.15f}')

Valor da integral: 0.746824132812427
Margem de erro: 0.000000000000008

In [4]:
# Cálculo da integral imprópria
I, erro = integrate.quad(f,0,np.inf)

# Exibição do valor calculado e da margem de erro
print(f'Valor da integral: {I:.15f}')
print(f'Margem de erro: {erro:.15f}')

Valor da integral: 0.886226925452758
Margem de erro: 0.000000007101318

### Otimização (SciPy)

In [5]:
# Definição da função a ser usada na busca de raízes
def f(x):
    return x**3 - x

In [6]:
# Busca de raízes da função
# Cada estimativa inicial pode levar a uma raiz diferente
# A convergência do método é indicada no campo "message"
# As raízes encontradas estão no vetor "x"
optimize.root(f,[-2,-0.2,5])

    fjac: array([[-9.99824592e-01,  9.67450043e-06, -1.87292786e-02],
       [-1.56129508e-05, -9.99999950e-01,  3.16921561e-04],
       [ 1.87292746e-02, -3.17158389e-04, -9.99824541e-01]])
     fun: array([-4.57536231e-11, -1.35362129e-11, -2.16959783e-12])
 message: 'The solution converged.'
    nfev: 23
     qtf: array([ 4.09871463e-08, -9.75550076e-11,  1.14788778e-09])
       r: array([-3.33441595e+00,  8.30479161e-05,  2.84577883e+01,  8.80000414e-01,
       -2.44489831e-04, -1.19996163e+00])
  status: 1
 success: True
       x: array([-1.00000000e+00,  1.35362129e-11,  1.00000000e+00])

In [7]:
# Lista de raízes, com arredondamento para 8 casas decimais
np.round(optimize.root(f,[-2,-0.2,5]).x,8)

array([-1.,  0.,  1.])

In [8]:
# Busca de pontos de mínimo local da função
optimize.minimize(f,1)

      fun: -0.3849001794597505
 hess_inv: array([[1]])
      jac: array([3.35276127e-08])
  message: 'Optimization terminated successfully.'
     nfev: 6
      nit: 1
     njev: 3
   status: 0
  success: True
        x: array([0.57735027])

In [9]:
# Ponto de mínimo local mais próximo da estimativa inicial 1
np.round(optimize.minimize(f,1).x[0],8)

0.57735027

In [10]:
# Valor mínimo local no ponto encontrado
np.round(f(optimize.minimize(f,1).x[0]),8)

-0.38490018

In [11]:
# Busca de um ponto de máximo local da função

# Basta buscar um ponto de mínimo do oposto da função
def g(x):
    return -f(x)
optimize.minimize(g,-1)

      fun: -0.3849001794597505
 hess_inv: array([[1]])
      jac: array([3.35276127e-08])
  message: 'Optimization terminated successfully.'
     nfev: 6
      nit: 1
     njev: 3
   status: 0
  success: True
        x: array([-0.57735027])

In [12]:
# Ponto de máximo local mais próximo da estimativa inicial 1
np.round(optimize.minimize(g,-1).x[0],8)

-0.57735027

In [13]:
# Valor máximo local no ponto encontrado
np.round(f(optimize.minimize(g,-1).x[0]),8)

0.38490018

### Estatística  (SciPy)

In [14]:
# Distribuição de probabilidade acumulada sob a distribuição normal pdrão
stats.norm.cdf(0.8)

0.7881446014166034

In [15]:
# Função densidade de probabilidade da distribuição normal pdrão
stats.norm.pdf(0.8)

0.28969155276148273

In [16]:
# Regressão linear
# O primeiro parâmetro é uma lista de valores de x
# O segundo parâmetro é uma lista de valores de y
stats.linregress([0,3,6],[4,2,1.2])

LinregressResult(slope=-0.4666666666666666, intercept=3.8, rvalue=-0.9707253433941508, pvalue=0.1544209583112668, stderr=0.1154700538379254, intercept_stderr=0.4472135954999589)

### Análise de dados  (Pandas)

In [17]:
# A biblioteca Pandas reúne as ferramentas de análise e manipulação de dados.

import pandas as pd

In [18]:
# Leitura de dados de um arquivo CSV para um DataFrame
AppleDF = pd.read_csv('AAPL.csv')

In [19]:
# Visualização do DataFrame
AppleDF

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-04-03,41.910000,42.187500,41.220001,42.097500,40.132431,121112000
1,2018-04-04,41.220001,43.002499,41.192501,42.902500,40.899864,138422000
2,2018-04-05,43.145000,43.557499,43.020000,43.200001,41.183464,107732800
3,2018-04-06,42.742500,43.119999,42.049999,42.095001,40.130051,140021200
4,2018-04-09,42.470001,43.272499,42.462502,42.512501,40.528065,116070800
...,...,...,...,...,...,...,...
1254,2023-03-27,159.940002,160.770004,157.869995,158.279999,158.279999,52390300
1255,2023-03-28,157.970001,158.490005,155.979996,157.649994,157.649994,45992200
1256,2023-03-29,159.369995,161.050003,159.350006,160.770004,160.770004,51305700
1257,2023-03-30,161.529999,162.470001,161.270004,162.360001,162.360001,49501700
1258,2023-03-31,162.440002,165.000000,161.910004,164.899994,164.899994,68694700

In [20]:
# Visualização apenas das primeiras linhas do DataFrame
AppleDF.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-04-03,41.910000,42.187500,41.220001,42.097500,40.132431,121112000
1,2018-04-04,41.220001,43.002499,41.192501,42.902500,40.899864,138422000
2,2018-04-05,43.145000,43.557499,43.020000,43.200001,41.183464,107732800
3,2018-04-06,42.742500,43.119999,42.049999,42.095001,40.130051,140021200
4,2018-04-09,42.470001,43.272499,42.462502,42.512501,40.528065,116070800

In [21]:
# Visualização apenas das últimas linhas do DataFrame
AppleDF.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
1254,2023-03-27,159.940002,160.770004,157.869995,158.279999,158.279999,52390300
1255,2023-03-28,157.970001,158.490005,155.979996,157.649994,157.649994,45992200
1256,2023-03-29,159.369995,161.050003,159.350006,160.770004,160.770004,51305700
1257,2023-03-30,161.529999,162.470001,161.270004,162.360001,162.360001,49501700
1258,2023-03-31,162.440002,165.000000,161.910004,164.899994,164.899994,68694700

In [22]:
# Visualização apenas de colunas selecionadas do DataFrame
AppleDF[['Date','Adj Close']]

            Date   Adj Close
0     2018-04-03   40.132431
1     2018-04-04   40.899864
2     2018-04-05   41.183464
3     2018-04-06   40.130051
4     2018-04-09   40.528065
...          ...         ...
1254  2023-03-27  158.279999
1255  2023-03-28  157.649994
1256  2023-03-29  160.770004
1257  2023-03-30  162.360001
1258  2023-03-31  164.899994

[1259 rows x 2 columns]

In [23]:
# Visualização apenas de colunas selecionadas do DataFrame, filtrado por um intervalo de datas
AppleDF[['Date','Adj Close']][(AppleDF['Date']>='2020-03-01') & (AppleDF['Date']<='2020-03-31')]

           Date  Adj Close
481  2020-03-02  73.246216
482  2020-03-03  70.919968
483  2020-03-04  74.209557
484  2020-03-05  71.802422
485  2020-03-06  70.848885
486  2020-03-09  65.245285
487  2020-03-10  69.944359
488  2020-03-11  67.515152
489  2020-03-12  60.847721
490  2020-03-13  68.137779
491  2020-03-16  59.372066
492  2020-03-17  61.982662
493  2020-03-18  60.465328
494  2020-03-19  60.002026
495  2020-03-20  56.192768
496  2020-03-23  54.999001
497  2020-03-24  60.516796
498  2020-03-25  60.183422
499  2020-03-26  63.350468
500  2020-03-27  60.727604
501  2020-03-30  62.460644
502  2020-03-31  62.333183

In [24]:
# Valor máximo da coluna selecionada do DataFrame, no intervalo de datas escolhido
AppleDF[['Adj Close']][(AppleDF['Date']>='2020-03-01') & (AppleDF['Date']<='2020-03-31')].max()

Adj Close    74.209557
dtype: float64

In [25]:
# Valor mínimo da coluna selecionada do DataFrame, no intervalo de datas escolhido
AppleDF[['Adj Close']][(AppleDF['Date']>='2020-03-01') & (AppleDF['Date']<='2020-03-31')].min()

Adj Close    54.999001
dtype: float64

In [26]:
# Salvamento do DataFrame em arquivo Excel
AppleDF.to_excel('AAPL.xlsx')

In [27]:
# Resumo estatístico das colunas do DataFrame
AppleDF.describe()

,Open,High,Low,Close,Adj Close,Volume
count,1259.000000,1259.000000,1259.000000,1259.000000,1259.000000,1.259000e+03
mean,103.144037,104.410975,101.954966,103.240302,101.913314,1.128419e+08
std,45.726678,46.318832,45.148137,45.757042,46.077477,5.427141e+07
min,35.994999,36.430000,35.500000,35.547501,34.257286,3.519590e+07
25%,54.039999,54.739999,53.270000,53.868752,51.914310,7.661875e+07
50%,115.750000,117.260002,114.129997,115.707497,113.964050,9.791850e+07
75%,145.540001,147.264999,144.120003,145.860001,144.885368,1.311514e+08
max,182.630005,182.940002,179.119995,182.009995,180.683868,4.265100e+08

In [28]:
# Matriz de correlações entre as colunas numéricas do DataFrame
AppleDF.corr()

               Open      High       Low     Close  Adj Close    Volume
Open       1.000000  0.999688  0.999623  0.999183   0.999139 -0.343543
High       0.999688  1.000000  0.999571  0.999621   0.999592 -0.336694
Low        0.999623  0.999571  1.000000  0.999632   0.999583 -0.352508
Close      0.999183  0.999621  0.999632  1.000000   0.999957 -0.345037
Adj Close  0.999139  0.999592  0.999583  0.999957   1.000000 -0.346147
Volume    -0.343543 -0.336694 -0.352508 -0.345037  -0.346147  1.000000

In [29]:
# Criação de um novo DataFrame
NovoDF = pd.DataFrame([[1,5,2],[2,3,4],[7,4,3],[7,3,5]],index = [0,1,2,3], columns = ['A', 'B', 'C'])

# Exibição do DataFrame criado
NovoDF

   A  B  C
0  1  5  2
1  2  3  4
2  7  4  3
3  7  3  5